#!/bin/sh -l
set -e

TOKEN=$1
REPO=$2
URL=https://api.github.com/repos/${REPO}
OUTPUT=repo.json
CODE=$(curl --silent --write-out '%{http_code}' --output $OUTPUT --header "Authorization: token ${TOKEN}" ${URL})
echo "HTTP Status: $CODE"

if [ $CODE -ne 200 ]; then
  echo "Failed to get repo info"
  exit 1
fi

echo "env: $GITHUB_OUTPUT"
PRIVATE=$(jq ".private" $OUTPUT)
rm $OUTPUT

if [ "$PRIVATE" = "true" ]; then
    echo "Repo is private"
    echo "is_public=false"
    echo "is_public=false">> "$GITHUB_OUTPUT"
    echo "REPO_IS_PUBLIC=false">> "$GITHUB_ENV"
    echo "is_private=true"
    echo "is_private=true">> "$GITHUB_OUTPUT"
    echo "REPO_IS_PRIVATE=true">> "$GITHUB_ENV"
    echo "status=private"
    echo "status=private" >> "$GITHUB_OUTPUT"
    echo "REPO_STATUS=private" >> "$GITHUB_ENV"

else
    echo "Repo is Public"
    echo "is_public=true"
    echo "is_public=true" >> "$GITHUB_OUTPUT"
    echo "REPO_IS_PUBLIC=true" >> "$GITHUB_ENV"
    echo "is_private=false"
    echo "is_private=false" >> "$GITHUB_OUTPUT"
    echo "REPO_IS_PRIVATE=false" >> "$GITHUB_ENV"
    echo "status=public"
    echo "status=public" >> "$GITHUB_OUTPUT"
    echo "REPO_STATUS=public" >> "$GITHUB_ENV"
fi

cat $GITHUB_OUTPUT