#!/bin/sh -l
set -e

TOKEN=$1
REPO=$2
URL=https://api.github.com/repos/${REPO}
OUTPUT=repo.json
CODE=$(curl --silent --write-out '%{http_code}' --output $OUTPUT --header "Authorization: token ${TOKEN}" ${URL})
echo "HTTP Status: $CODE"

if [ $CODE -ne 200 ]; then
  echo "Failed to get repo info"
  exit 1
fi

PRIVATE=$(jq ".private" $OUTPUT)
rm $OUTPUT

if [ "$PRIVATE" = "true" ]; then
    echo "Repo is private"
    {
      echo "is_public=false"
      echo "is_private=true"
      echo "status=private"
    } >> $GITHUB_OUTPUT
else
    echo "Repo is Public"
    {
      echo "is_public=true"
      echo "is_private=false"
      echo "status=public"
    } >> $GITHUB_OUTPUT
fi
